var allbills = [[ "Introduced in House", "Energy and Natural Resources Committee", 71 ],
[ "Judiciary Committee", "Reported to Floor", 104 ],
[ "Introduced in House", "House Administration Committee", 220 ],
[ "Introduced in House", "Small Business Committee", 69 ],
[ "Environment and Public Works Committee", "Reported to Floor", 4 ],
[ "Introduced in House", "Foreign Relations Committee", 33 ],
[ "Transportation and Infrastructure Committee", "Reported to Floor", 74 ],
[ "Introduced in House", "Agriculture Committee", 268 ],
[ "Introduced in House", "Appropriations Committee", 143 ],
[ "Agriculture Committee", "Reported to Floor", 20 ],
[ "Introduced in House", "Armed Services Committee", 360 ],
[ "Ways and Means Committee", "Reported to Floor", 44 ],
[ "Introduced in House", "Education and the Workforce Committee", 685 ],
[ "Natural Resources Committee", "Reported to Floor", 402 ],
[ "Introduced in House", "Science, Space, and Technology Committee", 139 ],
[ "Introduced in House", "Agriculture, Nutrition, and Forestry Committee", 9 ],
[ "Financial Services Committee", "Reported to Floor", 46 ],
[ "Energy and Commerce Committee", "Reported to Floor", 108 ],
[ "Introduced in House", "Health, Education, Labor, and Pensions Committee", 32 ],
[ "Homeland Security Committee", "Reported to Floor", 36 ],
[ "Introduced in House", "Homeland Security and Governmental Affairs Committee", 138 ],
[ "Introduced in House", "Intelligence (Permanent) Committee", 62 ],
[ "Introduced in House", "Banking, Housing, and Urban Affairs Committee", 45 ],
[ "Education and the Workforce Committee", "Reported to Floor", 28 ],
[ "Introduced in House", "Ways and Means Committee", 1361 ],
[ "Budget Committee", "Reported to Floor", 8 ],
[ "Introduced in House", "Homeland Security Committee", 108 ],
[ "Homeland Security and Governmental Affairs Committee", "Reported to Floor", 60 ],
[ "Science, Space, and Technology Committee", "Reported to Floor", 22 ],
[ "Introduced in House", "Transportation and Infrastructure Committee", 436 ],
[ "Introduced in House", "Ethics Committee", 1 ],
[ "Introduced in House", "Financial Services Committee", 529 ],
[ "Veterans' Affairs Committee", "Reported to Floor", 36 ],
[ "Introduced in House", "Intelligence Committee", 2 ],
[ "Indian Affairs Committee", "Reported to Floor", 4 ],
[ "Introduced in House", "Finance Committee", 16 ],
[ "Armed Services Committee", "Reported to Floor", 4 ],
[ "Small Business Committee", "Reported to Floor", 16 ],
[ "Foreign Affairs Committee", "Reported to Floor", 14 ],
[ "Introduced in House", "Environment and Public Works Committee", 23 ],
[ "Introduced in House", "Budget Committee", 163 ],
[ "Introduced in House", "Energy and Commerce Committee", 1085 ],
[ "Introduced in House", "Oversight and Government Reform Committee", 558 ],
[ "Introduced in House", "Indian Affairs Committee", 8 ],
[ "Intelligence (Permanent) Committee", "Reported to Floor", 5 ],
[ "Energy and Natural Resources Committee", "Reported to Floor", 28 ],
[ "Foreign Relations Committee", "Reported to Floor", 6 ],
[ "Introduced in House", "Rules Committee", 108 ],
[ "Appropriations Committee", "Reported to Floor", 8 ],
[ "Introduced in House", "Judiciary Committee", 968 ],
[ "Introduced in House", "Veterans' Affairs Committee", 378 ],
[ "Commerce, Science, and Transportation Committee", "Reported to Floor", 2 ],
[ "Health, Education, Labor, and Pensions Committee", "Reported to Floor", 8 ],
[ "Introduced in House", "Commerce, Science, and Transportation Committee", 38 ],
[ "Oversight and Government Reform Committee", "Reported to Floor", 72 ],
[ "House Administration Committee", "Reported to Floor", 5 ],
[ "Introduced in House", "Foreign Affairs Committee", 319 ],
[ "Introduced in House", "Natural Resources Committee", 709 ],
[ "Reported to Floor", "Passed House",581]]